name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Homebrew packages
      run: |
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        brew update
        brew install ffmpeg lld llvm meson vapoursynth xxhash

    - name: Set environment variables for Clang/LLVM
      run: |
        echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV
        echo "PATH=/opt/homebrew/opt/llvm/bin:$PATH" >> $GITHUB_ENV

    - name: Build
      run: |
        meson setup -Dcpp_link_args=-fuse-ld=lld build
        ninja -C build
